# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_g7TsD7OPfVTBfnq_oWKoPrrNTyQAJx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
data=pd.read_csv("/content/drive/MyDrive/study_house.csv.txt")
print(data.head())
x=data[['Hours_Studied']]
y=data['Exam_Score']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)
print("Training Data :")
print(pd.concat([x_train,y_train],axis=1).head())
print("Testing Data :")
print(pd.concat([x_test,y_test],axis=1).head())
y_pred=model.predict(x_test)
plt.figure(figsize=(8,6))
plt.scatter(x_test,y_test,color='green',label='Actual Scores')
plt.plot(x_test,y_pred,color='red',label='Regression Line')
plt.xlabel('Hours Studied')
plt.ylabel('Exam Score')
plt.title('Simple Linear Regression : Actual Vs Predicted Scores')
plt.legend()
plt.show()
new_house_sqft=pd.DataFrame({'Hours_Studied':[10]})
predict_price=model.predict(new_house_sqft)
print(f"\nPredicted Exam Score For 10 Hours Studied : {predict_price}")



import pickle

# Define the filename
filename = 'linear_regression_model.pkl'

# Save the trained model to a file
pickle.dump(model, open(filename, 'wb'))

print(f"Model saved to {filename}")